const constants = {
    ADD_TIMER: "ADD_TIMER",
    REMOVE_TIMER: "REMOVE_TIMER",
    RESET_TIMERS: "RESET_TIMERS",
    TOGGLE_VIBRATE: "TOGGLE_VIBRATE",
    SET_VIBRATE: "SET_VIBRATE",
    TOGGLE_SOUND: "TOGGLE_SOUND",
    SET_SOUND: "SET_SOUND"
}

export default constants;